<!DOCTYPE html>
<html>
    <head>
        <title>E-PF2431</title>
        <meta name="language" content="English">
        <meta name="description" content="It is a website about genealogy">
        <meta name="keywords" content="blog">
        <meta name="author" content="Yanis">
        <link rel="stylesheet" href="/assets/font-awesome-4.5.0/css/font-awesome.css">	
        <link rel="stylesheet" href="/assets/css/nivo-slider.css" type="text/css" media="screen" />
        <link rel="stylesheet" href="/assets/css/style.css">
        <script src="/assets/js/jquery.js" type="text/javascript"></script>
        <script src="/assets/js/jquery.nivo.slider.js" type="text/javascript"></script>
    </head>
    <body>
        <header class="container">
            <a href="index.php?r=home">
                <div>
                    <img src="/assets/images/logo.png" alt="Logo"/>
                    <h2>E-PF2431</h2>
                    <p>Historic, genealogic & genetic website</p>
                </div>
            </a>
            <div>
                <div>
                    <a href="#" target="_blank"><i class="fa fa-facebook"></i></a>
                    <a href="#" target="_blank"><i class="fa fa-twitter"></i></a>
                    <a href="#" target="_blank"><i class="fa fa-linkedin"></i></a>
                </div>
                <div>
                    <form action="index.php?r=article-search" method="post">
                        <input type="text" name="keyword" placeholder="Search keyword..."/>
                        <input type="submit" name="submit" value="Search"/>
                    </form>
                </div>
            </div>
            <nav>
                <ul>
                    <li><a id="active" href="index.php">Home</a></li>
                    <li><a href="index.php?r=about">About</a></li>	
                    <li><a href="index.php?r=contact">Contact</a></li>
                </ul>
            </nav>
        </header>
        <div class="container">
            <main>
                <?= $contentPage ?>
            </main>
            <aside>
                <section>
                    <h2><span>Categories</span></h2>
                    <ul>
                        <li><a href="index.php?r=article-category/id/1">Genealogy</a></li>
                        <li><a href="index.php?r=article-category/id/2">y-dna</a></li>
                        <li><a href="index.php?r=article-category/id/3">History</a></li>			
                    </ul>
                </section>		
                <section>
                    <h2><span>Latest articles</span></h2>
                    <div>
                        <?php foreach($lastArticles as $item): ?>
                            <h3><a href="index.php?r=article/id/<?= $item['id'] ?>"><?= htmlspecialchars($item['title']) ?></a></h3>
                            <a href="#"><img src="/assets/images/<?= $item['image'] ?>" alt="post image"/></a>
                            <p><?= htmlspecialchars(substr($item['content'], 0, 100)) ?></p>	
                        <?php endforeach; ?>
                    </div>
                </section>
            </aside>
        </div>
        <footer class="container">
            <nav>
                <ul>
                    <li><a href="index.php">Home</a></li>
                    <li><a href="about.php">About</a></li>
                    <li><a href="contact.php">Contact</a></li>
                    <li><a href="#">Privacy</a></li>
                </ul>
            </nav>
            <p>&copy; Copyright yakem.</p>
        </footer>
        <script type="text/javascript" src="/assets/js/scrolltop.js"></script>
    </body>
</html>
<?php unset($_SESSION['values']); ?>
<?php unset($_SESSION['errors']); ?>